Table:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
            - AttributName: id
              AttributType: S
            - AttributName: commitMessage
              AttributType: S
        KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: commitMessage
              KeyType: RANGE
        
        ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.dbReadCapacityUnits}
            WriteCapacityUnits: ${self:custom.dbWriteCapacityUnits}